# ####################
# Config file "YAML" #
# ####################

user_linux: "${USER}"         # OS env. variable from Linux
user_windows: "${USERNAME}"   # OS env. variable from Windows
var_env: "${PWDTEST}"         # User env. var
placeholder: "My Application_${PWDTEST}"

aDictionnary: {"Name": "Karl ", "Age": 24, "Address": " France "}

receipt:     Oz-Ware Purchase Invoice
date:        2012-08-06
customer:
    # This is a comment
    given:   Dorothy
    family:  Gale

items:
    - part_no:   " A4786"
      descrip:   "Water Bucket (Filled) "
      price:     1.47
      quantity:  4

    - part_no:   E1628
      descrip:   High Heeled "Ruby" Slippers
      size:      8
      price:     100.27
      quantity:  1

bill-to:  &id001
    street: |
            123 Tornado Alley
            Suite 16
    city:   East Centerville
    state:  KS

ship-to:  *id001

customerName: ${customer.given}

specialDelivery:  >
    Follow the Yellow Brick
    Road to the Emerald City.
    Pay no attention to the
    man behind the curtain.

